CREATE TABLE USERS (
  ID INT NOT NULL,
  NAME VARCHAR (50),
  PASSWORD VARCHAR(128),
  AVATAR_URL VARCHAR(50),
  PRIMARY KEY (ID)
);

CREATE TABLE SNIPPETS (
  CONTENT VARCHAR (200),
  ID INT NOT NULL,
  USER_ID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

